package webapp

const homePage = `<!doctype html>
<html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Certarium</title><style>
:root{font-family:system-ui,sans-serif;color:#18202a;background:#f5f7fa}body{margin:0}.wrap{max-width:980px;margin:40px auto;padding:0 20px}header{display:flex;align-items:center;justify-content:space-between}.badge{padding:6px 11px;border-radius:99px;background:#e7edf4}.ok{background:#dff5e8;color:#176b3a}.card{background:white;border:1px solid #dbe2ea;border-radius:14px;padding:22px;margin:18px 0;box-shadow:0 8px 28px #17202a0a}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px}label{display:block;font-size:14px;margin:10px 0 4px}input,select,button{box-sizing:border-box;width:100%;padding:10px;border:1px solid #bdc8d4;border-radius:8px;font:inherit}button{margin-top:16px;background:#185adb;color:white;border:0;cursor:pointer}.row{display:flex;gap:10px;align-items:center}.row input{width:auto}.muted{color:#637083;font-size:14px}ul{padding-left:20px}.error{color:#a92323;white-space:pre-wrap}.success{color:#176b3a}a{color:#185adb}
</style></head><body><main class="wrap"><header><div><h1>Certarium</h1><p class="muted">标准 RSA 与国密 TLCP 实验证书工作台</p></div><span id="status" class="badge">检查中</span></header>
<section id="init" class="card"><h2>1. 初始化实验 CA</h2><p class="muted">创建相互独立、加密保存的 RSA 与 SM2 根 CA。此操作只能执行一次，请先确认已经规划备份位置。</p><form id="init-form"><label for="org">组织名称</label><input id="org" name="organization" required maxlength="64" value="Certarium Lab"><button>初始化 CA</button></form></section>
<section id="issue" class="card" hidden><h2>签发服务器证书</h2><form id="issue-form"><div class="grid"><div><label for="kind">证书类型</label><select id="kind"><option value="rsa">标准 RSA</option><option value="tlcp">TLCP 国密双证书</option></select></div><div><label for="name">安全标识</label><input id="name" required maxlength="64" placeholder="gateway-01"></div><div><label for="cn">通用名（CN）</label><input id="cn" required maxlength="253" placeholder="gateway.test"></div><div><label for="days">有效天数</label><input id="days" type="number" min="1" max="825" value="397" required></div><div><label for="dns">DNS SAN（逗号分隔）</label><input id="dns" placeholder="gateway.test,api.test"></div><div><label for="ips">IP SAN（逗号分隔）</label><input id="ips" placeholder="192.0.2.10,2001:db8::10"></div></div><label class="row"><input id="confirm" type="checkbox" required>我确认由服务端生成并保存叶子证书私钥</label><button>签发证书</button></form></section>
<section class="card"><h2>2. 导入实验根 CA</h2><p class="muted">把对应根证书导入测试客户端的“受信任的根证书颁发机构”。请勿在生产终端分发实验根证书。</p><p><a href="/api/v1/ca/rsa">下载 RSA 根 CA</a> · <a href="/api/v1/ca/sm2">下载 SM2 根 CA</a> · <a href="/api/v1/crl/rsa">RSA CRL</a> · <a href="/api/v1/crl/sm2">SM2 CRL</a></p></section>
<section class="card"><h2>3. 已签发证书</h2><p class="muted">整包下载包含私钥，仅应传给明确授权的实验系统。</p><button id="refresh" type="button">刷新列表</button><ul id="records"><li class="muted">暂无记录</li></ul></section><p id="message" role="status"></p></main><script src="/app.js" defer></script></body></html>`

const applicationJS = `
const q=(s)=>document.querySelector(s);const message=q('#message');
function show(text,ok=false){message.textContent=text;message.className=ok?'success':'error'}
function parts(value){return value.split(',').map(v=>v.trim()).filter(Boolean)}
async function api(path,options={}){const response=await fetch(path,options);let data={};try{data=await response.json()}catch(_){}if(!response.ok)throw new Error(data.message||('HTTP '+response.status));return data}
async function status(){try{const data=await api('/api/v1/status');q('#status').textContent=data.initialized?'CA 已初始化':'等待初始化';q('#status').className=data.initialized?'badge ok':'badge';q('#init').hidden=data.initialized;q('#issue').hidden=!data.initialized;if(data.initialized)await list()}catch(error){show(error.message)}}
function fileLink(item,id,name){const link=document.createElement('a');link.href='/api/v1/certificates/'+encodeURIComponent(id)+'/files/'+encodeURIComponent(name);link.textContent=name;item.append(document.createTextNode(' · '),link)}
async function revoke(id){if(!window.confirm('确认永久吊销 '+id+'？吊销后无法恢复。'))return;try{await api('/api/v1/certificates/'+encodeURIComponent(id)+'/revoke',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});show('证书已吊销并更新 CRL',true);await list()}catch(error){show(error.message)}}
async function list(){try{const data=await api('/api/v1/certificates');const root=q('#records');root.replaceChildren();if(!data.certificates.length){const item=document.createElement('li');item.textContent='暂无记录';item.className='muted';root.append(item);return}for(const cert of data.certificates){const item=document.createElement('li');const title=document.createElement('strong');title.textContent=cert.id+' · '+cert.kind+' · '+cert.state+' · '+(cert.common_name||'');item.append(title);const detail=document.createElement('p');detail.className='muted';detail.textContent='序列号: '+(cert.serials||[]).join(', ')+' · 用途: '+(cert.purpose||'-')+' · SAN: '+[...(cert.dns_names||[]),...(cert.ip_addresses||[])].join(', ')+' · 有效期: '+(cert.issued_at||'-')+' → '+(cert.expires_at||'-');item.append(detail);const bundle=document.createElement('a');bundle.href='/api/v1/certificates/'+encodeURIComponent(cert.id)+'/bundle.zip';bundle.textContent='下载完整证书包（含私钥）';item.append(bundle);const files=cert.kind==='rsa'?['server-rsa.crt','server-rsa.key']:['server-sign.crt','server-sign.key','server-enc.crt','server-enc.key'];for(const file of files)fileLink(item,cert.id,file);if(cert.state!=='revoked'){const button=document.createElement('button');button.type='button';button.textContent='吊销此证书';button.addEventListener('click',()=>revoke(cert.id));item.append(document.createElement('br'),button)}root.append(item)}}catch(error){show(error.message)}}
q('#init-form').addEventListener('submit',async(event)=>{event.preventDefault();try{await api('/api/v1/initialize',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({organization:q('#org').value})});show('CA 初始化成功',true);await status()}catch(error){show(error.message)}});
q('#issue-form').addEventListener('submit',async(event)=>{event.preventDefault();const kind=q('#kind').value;const payload={name:q('#name').value,common_name:q('#cn').value,dns_names:parts(q('#dns').value),ip_addresses:parts(q('#ips').value),valid_days:Number(q('#days').value),confirm_server_key_generation:q('#confirm').checked};try{await api('/api/v1/certificates/'+kind,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});show('证书签发成功',true);event.target.reset();q('#days').value='397';await list()}catch(error){show(error.message)}});
q('#refresh').addEventListener('click',list);status();`
